USE trrs;
DROP TABLE IF EXISTS commit;
DROP TABLE IF EXISTS publish;
DROP TABLE IF EXISTS teach;
DROP TABLE IF EXISTS course;
DROP TABLE IF EXISTS paper;
DROP TABLE IF EXISTS project;
DROP TABLE IF EXISTS teacher;