package priv.jeffrey.trrs.enums;

public enum TeacherTitle {
    POSTDOCTORAL,
    ASSISTANT_PROFESSOR,
    LECTURER,
    ASSOCIATE_PROFESSOR,
    DISTINGUISHED_PROFESSOR,
    PROFESSOR,
    ASSISTANT_RESEARCHER,
    DISTINGUISHED_ASSOCIATE_RESEARCHER,
    ASSOCIATE_RESEARCHER,
    DISTINGUISHED_RESEARCHER,
    RESEARCHER,
}
